version: '2'

services:
  nginx:
    image: dydx/alpine-nginx-phpfpm
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./sites:/etc/nginx/sites-enabled
    network_mode: "host"

  artisan:
    image: spiralout/dartisan
    volumes:
      - ./www:/var/www

  mysql:
    image: spiralout/alpine-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  composer:
    image: spiralout/dcomposer
    volumes:
      - ./www:/var/www

  nodejs:  
    image: spiralout/dnodejs
    volumes:
      - ./www:/var/www

  redis:
    image: spiralout/alpine-redis
    volumes:
      - ./redis-data:/data

volumes:
  www:
  sites:
  redis-data:
